# Generated by Django 6.0.5 on 2026-05-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closing_hour',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hour',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
